apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apimanager-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apimanager
    spec:
      containers:
      - name: apimanager-pod
        image: yessid/apimanager:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: apimanager
  labels:
    app: apimanager-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30000
    protocol: TCP
  selector:
    app: apimanager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-pod
        image: yessid/userservice:latest
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  type: NodePort
  ports:
  - port: 8100
    nodePort: 30100
    nodePort: 
    protocol: TCP
  selector:
    app: user-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-pod
        image: yessid/productservice:latest
        ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  type: NodePort
  ports:
  - port: 8200
    nodePort: 30200
    protocol: TCP
  selector:
    app: product-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-pod
        image: yessid/orderservice:latest
        ports:
        - containerPort: 8300
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order
spec:
  type: NodePort
  ports:
  - port: 8300
    nodePort: 30300
    protocol: TCP
  selector:
    app: order-app